# Generated by Django 6.0.1 on 2026-03-15 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel', models.CharField(choices=[('1', 'Primario'), ('2', 'Secundario'), ('3', 'Terciario')], max_length=1)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='backFeelifyme.emocion')),
            ],
            options={
                'verbose_name': 'Emocion',
                'verbose_name_plural': 'Emociones',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre', 'apellido1'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionEmocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_relacionadas', to='backFeelifyme.emocion')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emociones_asociadas', to='backFeelifyme.recomendacion')),
            ],
            options={
                'verbose_name': 'Relación recomendación-emoción',
                'verbose_name_plural': 'Relaciones recomendación-emoción',
                'ordering': ['recomendacion'],
                'unique_together': {('recomendacion', 'emocion')},
            },
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='emociones',
            field=models.ManyToManyField(related_name='recomendaciones', through='backFeelifyme.RecomendacionEmocion', to='backFeelifyme.emocion'),
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, help_text='Escribe una reflexión o suceso del día', null=True, verbose_name='Nota diaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro diario',
                'verbose_name_plural': 'Registros diarios',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_que_lo_tienen', to='backFeelifyme.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_obtenidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro usuario',
                'verbose_name_plural': 'Logros usuarios',
                'ordering': ['usuario'],
                'unique_together': {('usuario', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='EmocionRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asociados', to='backFeelifyme.emocion')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emociones_registradas', to='backFeelifyme.registrodiario')),
            ],
            options={
                'verbose_name': 'Emoción registrada',
                'verbose_name_plural': 'Emociones registradas',
                'unique_together': {('registro', 'emocion')},
            },
        ),
        migrations.CreateModel(
            name='ActividadRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asociados', to='backFeelifyme.actividad')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_realizadas', to='backFeelifyme.registrodiario')),
            ],
            options={
                'verbose_name': 'Actividad realizada',
                'verbose_name_plural': 'Actividades realizadas',
                'unique_together': {('registro', 'actividad')},
            },
        ),
    ]
