# Generated by Django 6.0.3 on 2026-04-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backFeelifyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emocionregistrada',
            unique_together=set(),
        ),
    ]
