# Generated by Django 6.0.3 on 2026-04-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backFeelifyme', '0002_alter_emocionregistrada_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrodiario',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='emocionregistrada',
            unique_together={('registro', 'emocion')},
        ),
    ]
